### PR TITLE
elm-package support

### PR DESCRIPTION
**Pull request by texastoland**
### NOT Ready to merge
- [x] `elm-package install`
- [x] Open package docs in browser
- [x] Pull stats from GitHub
- [x] Filter and sort based on installed dependencies
- [x] Remember selected build system

### CODE REVIEW

**Comment by dnalot** [comment]
@deadfoxygrandpa This should be good to go when you are.

**Comment by dnalot** [comment]
Never mind I remember one more thing needs fixed…

**Comment by deadfoxygrandpa** [comment]
@AppShipIt I was just revisiting this. Is the "one more thing" that needs to be fixed the "Remember selected build system" item? Would you mind explaining that to me so I can fix it? I'd like to incorporate this stuff and get it working.

Thanks again for all the help you provided.

**Comment by AppShipIt** [comment]
Likewise thanks for the opportunity to participate in an interesting project Alex!

ST's builtin Build system machinery does a lot of lifting for us but wasn't very extensible. I used it for both `elm_make` and `elm_package` commands. I wanted a GUI to pick which package to install from the web but Build commands neither have any way to inject callbacks nor receive dynamic arguments. I built a custom `ElmPackageInstallCommand` that ([source](https://github.com/deadfoxygrandpa/Elm.tmLanguage/blob/87df1457e99449aa1eb6b02b66055a43a6ec171b/elm_package.py#L138-L141)):

1. sets the Build system to `elm_package`,
2. passes dynamic arguments by attaching them as `settings` on the `view` (don't try using static variables for this!),
3. and runs the build system selected in step 1.

The unexpected side effect is next time you run the build it tries `elm_package` instead of `elm_make`. In reality `elm_make` should probably always be default. `ElmPackageCommand` could probably just set in back on `run`?

NB last I checked @evancz was revamping their project file and our parser will need updated accordingly.

**Comment by deadfoxygrandpa** [comment]
I fixed this today by going in a slightly different direction, which was calling default_exec.ExecCommand's run method for the elm package command instead of going through the build system. It's functionally very similar and still uses the build output panel the same way, it just doesn't set the build system so it bypasses the issue you had.

Thanks again!

**Pull request closed without merging**
