### PR TITLE
Syntax highlighting for `exposing`

### PR DESCRIPTION
**Pull request by rtfeldman**
My first PR thanks to lots of guidance from @dnalot...feedback welcome! :smiley: 

**Before:**
screen shot 2015-08-31 at 3 10 27 am

**After:**
screen shot 2015-08-31 at 3 12 56 am

### CODE REVIEW

**Comment by dnalot** [comment]
I'll look at this today and include it in beta!

**Comment by dnalot** [comment]
PS thank you I'd love to help you plan future features 👐

**Comment by rtfeldman** [comment]
@dnalot I have another branch with the awesome syntax highlighting (big hit at the office today...really makes things more readable!) - but it's based on this branch. Should I make a PR for that anyway or wait for this to get merged?

**Comment by dnalot** [comment]
Rebase your other branch onto this one and I'll look at both together!

**Comment by dnalot** [comment]
Closing in favor of #44. In the future you should be able to rebase onto the same branch and not open a new PR. The PR will just track the current branch :+1:

**Comment by dnalot** [comment]
Fixes #21 🎉

**Pull request closed without merging**
