### PR TITLE
Build

### PR DESCRIPTION
**Pull request by dnalot**
This is the big one. I'll just list features:

0. Two standard build commands triggered with <kbd>Super+[Shift]+B</kbd> or <kbd>Super+[Shift]+F7</kbd>.
  * The first just check errors. Credit to @rtfeldman's [tweet](https://twitter.com/rtfeldman/status/624026168652660740)!
  * `Run` additionally builds output to an intelligent path.
0. Errors are formatted for small space. They're navigable with <kbd>Super+[Shift]+F4</kbd>. Error highlighting is integrated with [Highlight Build Errors](https://packagecontrol.io/packages/Highlight%20Build%20Errors) (ST3 only) plugin if installed.
0. Compile messages are both highlighted and colored including embedded source 🎨
0. Ouput paths are configurable in `elm-package.json`. Keys not documented? No fear! There's a UI labeled `Elm Build System` in the Command Palette. It only requires a valid config in any ancestor directory of the edited file.
0. Launch generated HTML in your browser from an Elm source file. It requires [SideBarEnhancements](https://packagecontrol.io/packages/SideBarEnhancements) (ST3 only) if installed or alternatively [View In Browser](https://packagecontrol.io/packages/View%20In%20Browser) plugin. Not building HTML? That path is configurable in the Command Palete too.
0. Fully ST2/ST3 compatible.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Tried it out, got this in the console:

```
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n) elm-make: <stdin>: hGetLine: end of file
[Finished in 1.0s with exit code 1]
[shell_cmd: elm-make]
[dir: /Users/rtfeldman/code/elm-core/src]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

I've seen the `hGetLine: end of file` error before (it's a Haskell thing), and we've worked around it by setting the LANG env var. I tried doing that in the build config, to no avail:

```
{
  "env": {
    "LANG": "en_US.UTF-8"
  },
  "shell_cmd": "elm-make"
}
```

...but this time it didn't help.

Anyway, the error was happening because the file I was editing (`Maybe.elm` in `core`) happened to be in the `src/` directory instead of the project root. `elm-make` needs to run in whatever directory `elm-package.json` lives in, so I hacked around it by doing this:

```
{
  "working_dir": "../",
  "shell_cmd": "elm-make"
}
```

...although naturally that's not a scalable solution. :smile:

**Comment by rtfeldman** [comment]
At that point the build ran and I saw the output in the console, which was pretty sweet!

I have Highlight Build Errors installed, but didn't see any inline. (I also tried uninstalling/reinstalling Highlight Build Errors, uninstalling/reinstalling `elm-sublime`, and restarting Sublime Text 3, but still no highlighting.)

Awesome progress @dnalot! :smiley:

**Comment by rtfeldman** [comment]
Same deal with SublimeREPL: I have it installed, but don't see Elm integrations.

screen shot 2015-08-03 at 9 04 30 pm

**Comment by rtfeldman** [comment]
Also, for reference, this is the version I had installed:

screen shot 2015-08-03 at 9 06 04 pm

**Comment by dnalot** [comment]
Mind reporting each in [my fork](https://github.com/dnalot/elm-sublime)?

0. Re. `src` folder: Looking now!
1. Re. Highlighting: do <kbd>F4</kbd>/<kbd>Shift+F4</kbd> select your errors in the build panel?
2. Re. REPL: do you see anything Elm or REPL related in the Console (<kbd>Ctrl+`</kbd>), especially at startup?

**Comment by dnalot** [comment]
Hit me up on chat if you have a minute for me to check it out. Having trouble repro-ing.

**Comment by dnalot** [comment]
Status:

0. I couldn't repro the `hGetLine` issue. I'm supposed to be passing the `--yes` flag? I meant to account for it if you can raise the issue.
0. Looks like an issue with `elm-make` prepending JSON with a message. I have a solution for that. Reported upstream elm-lang/elm-make#38. Issue in mine wouldn't hurt.
0. Thanks for making dnalot/elm-sublime#1. I think it's an initialization order thing. I'd seen it intermittently but your log clarified it. I know one solution it's just lame.

**Comment by deadfoxygrandpa** [comment]
I just remembered this, and so I don't forget it I'll write it down. the `--output /dev/null` trick  doesn't work on Windows, but I just tried `--output NUL` and that seems to work, so we should probably do it that way on Windows.

**Comment by dnalot** [comment]
I already did it. Don't merge yet though! I just rebased.

**Comment by dnalot** [comment]
@rtfeldman All issues should be fixed 🙏

**Comment by vilterp** [comment]
Is it possible to hyperlink from errors in the console to the code?

**Comment by rtfeldman** [comment]
That would be *very* nice, if possible!

**Comment by dnalot** [comment]
Report it in either repo and I'll tag it as a feature!

**Comment by dnalot** [comment]
The answer is yes but I'm still evaluating how to do it with the least amount of code.

**Comment by vilterp** [comment]
[Reported in your fork](github.com/dnalot/elm-sublime/issues/3)

**Comment by dnalot** [comment]
@deadfoxygrandpa This one's ready to merge. I'll open a separate PR for a ST3 error in existing code. Also looking into #28 if you can take #29?

**Comment by deadfoxygrandpa** [comment]
OK, I'll merge it in. Thanks a lot for all this work.

**Pull request merged**
